### ISSUE TITLE
Push an update for node-16

### ISSUE THREAD

**Issue by DavidBeale** [NikolajDL/gcloud-sdk-nodejs#1]
Hi,

Thanks for the image. Are you able to push an update for the `node-16` tag?

**Comment by NikolajDL** [comment]
Hi,

I've now pushed an updated images for the `node-16` tag, so it now features node 16.17. I've also created the `lts` tag (which is essentially the same version as of right now).

Have a nice evening.

**Comment by DavidBeale** [comment]
Great, thanks 👍
